### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by seisfeld** [Jerware/GameFrameV2_WiFi#1]
Hi Jeremy,

I know this is for issues and not feedback, but anyways, I quickly wanted to let you know that I really like my GameFrame since Day 1 and really appreciate you keep maintaining it (although not toooo frequently ;)). I immediately installed the recent pong clock update and love it. Keep up the good projects. Greetings from Germany.

Stephan

**Comment by Jerware** [comment]
That's wonderful to hear! :)
