### ISSUE TITLE
Ledseq.com down, Firmware Manager?

### ISSUE THREAD

**Issue by Kugelblitz360** [Jerware/GameFrameV2_WiFi#3]
Hello Jeremy, any idea how to access the/a firmware manager now that ledseq.com is down?

**Comment by Jerware** [comment]
Sorry about that. I contacted my web host and they fixed the problem. Site is back up now. If you ever need the manager, the HTML file is actually in the 00system/wifi folder on your Game Frame SD card. Don't think you can access it over WIFI but you can always pop it in a PC and open it that way.

**Comment by Kugelblitz360** [comment]
Oh, very cool - I thought you had given up Gameframe for good with the new job (late Congrats btw. Hope you are excited about the LEGO announcement from today).
